"""Optional semantic embedding matching service using Sentence-Transformers.

Computes semantic dense vector cosine similarity between candidate resume text
and job description text using pretrained sentence-transformers models (e.g. all-MiniLM-L6-v2).

CRITICAL ARCHITECTURAL CONSTRAINTS:
1. Optional Dependency: sentence-transformers is NOT mandatory for the core application or API.
2. Lazy Loading: The model is only loaded if explicitly requested; startup is never blocked.
3. Graceful Degradation: If sentence-transformers or torch is missing, is_available() returns
   False with an informative actionable message.
4. Academic Disclaimer: Dense vector cosine similarity represents geometric proximity in embedding
   space; it does NOT measure candidate qualification or predict hiring decisions.
"""

from typing import Optional, Tuple
import numpy as np

DEFAULT_MODEL_NAME = "all-MiniLM-L6-v2"


class SemanticEmbeddingMatcher:
    """Service providing dense semantic embedding similarity using Sentence-Transformers."""

    def __init__(self, model_name: str = DEFAULT_MODEL_NAME) -> None:
        self.model_name = model_name
        self._model = None
        self._load_error: Optional[str] = None
        self.disclaimer = (
            "Semantic embedding similarity reflects the cosine distance between dense vector "
            f"representations generated by '{self.model_name}'. It captures semantic and paraphrastic "
            "proximity in latent space, but does not evaluate candidate qualification, experience depth, "
            "or hiring probability."
        )

    def is_available(self) -> bool:
        """Check whether the optional sentence-transformers and torch libraries are installed."""
        try:
            import sentence_transformers  # noqa: F401
            import torch  # noqa: F401
            return True
        except ImportError:
            return False

    def get_unavailable_reason(self) -> Optional[str]:
        """Return actionable explanation if optional dependencies are missing."""
        if self.is_available():
            return None
        return (
            "Optional dependency 'sentence-transformers' or 'torch' is not installed. "
            "To enable semantic embedding evaluation, install them in your Python environment via:\n"
            "    pip install sentence-transformers torch"
        )

    def _get_model(self):
        """Lazily load the SentenceTransformer model on first usage."""
        if self._model is not None:
            return self._model

        if not self.is_available():
            raise RuntimeError(self.get_unavailable_reason())

        from sentence_transformers import SentenceTransformer

        try:
            self._model = SentenceTransformer(self.model_name)
            return self._model
        except Exception as e:
            self._load_error = str(e)
            raise RuntimeError(
                f"Failed to load sentence-transformers model '{self.model_name}': {e}. "
                "Ensure local weights cache or internet access is available."
            ) from e

    def compute_similarity(
        self,
        resume_text: str,
        job_description: str,
    ) -> Tuple[float, str]:
        """Compute cosine similarity between normalized dense sentence embeddings.

        Args:
            resume_text: Plain text from resume document.
            job_description: Plain text of target job posting.

        Returns:
            Tuple of (similarity_float_0_to_1, explanatory_string).
        """
        clean_resume = resume_text.strip()
        clean_jd = job_description.strip()

        if not clean_resume or not clean_jd:
            return 0.0, "One or both input texts are empty. Semantic embedding similarity is 0.0."

        model = self._get_model()

        # Generate L2-normalized dense embeddings (shape: [dim])
        embeddings = model.encode(
            [clean_resume, clean_jd],
            normalize_embeddings=True,
            show_progress_bar=False,
        )

        emb_resume = embeddings[0]
        emb_jd = embeddings[1]

        # Since embeddings are unit normalized, cosine similarity is their dot product
        raw_cosine = float(np.dot(emb_resume, emb_jd))
        bounded_sim = round(max(0.0, min(1.0, raw_cosine)), 4)

        explanation = (
            f"Dense semantic cosine similarity is {bounded_sim:.4f} (or {bounded_sim * 100:.1f}%) "
            f"computed using '{self.model_name}'. Vectors are L2-normalized."
        )
        return bounded_sim, explanation


# Singleton instance
semantic_embedding_matcher = SemanticEmbeddingMatcher()
